app/main/__init__.py
from flask import Blueprint
from app.data.models import Permission


main = Blueprint('main', __name__, template_folder='templates')

from . import views

@main.app_context_processor
def inject_permissions():
	return dict(Permission=Permission)

app/main/views.py
from flask import render_template, send_from_directory, request, json
from app import app
from app.main import main
from app.cache import cache
from flask_login import current_user, login_required
from app.data.models import db, Permission, Advert, Cart, Date_available, Experience, Flyer, Imageexp, Rate, Shop, Slideshow, Story
from flask_mail import Message
from app import mail
from app.decorators import admin_required, permission_required

@main.route("/message")
def message():

    msg = Message("Hello",
                  sender="from@example.com",
                  recipients=["quinton.ssebaggala@gmail.com"])
    msg.body = "testing"
    msg.html = "<b>testing</b>"
    
    return mail.send(msg)

@main.route('/')
# @login_required
# @admin_required
@cache.cached(300, key_prefix='index')
def index():
    slideshow = Slideshow.query.order_by(Slideshow.created_on.desc()).limit(3).all()
    stories = Story.query.order_by(Story.created_on.desc()).limit(12).all()
    experience = Imageexp.query.order_by(Imageexp.created_on.desc()).limit(8).all()
    shop = Shop.query.order_by(Shop.created_on.desc()).limit(12).all()
    flyers = Flyer.query.order_by(Flyer.created_on.desc()).limit(2).all()
    adverts = Advert.query.order_by(Advert.created_on.desc()).limit(3).all()
    return render_template('main/body.html', slideshow=slideshow, stories=stories, 
							experience=experience, shop=shop, flyers=flyers, adverts=adverts)


@main.route('/test')
def test():
    data = Experience.query.order_by(Experience.created_on.desc()).limit(5).all()
    return render_template('test.html', data=data)

@main.route('/shop/')
@login_required
# @permission_required(Permission.FOLLOW)
def shop():
    page_num = int(request.args.get('page', 1))
    # shop = Shop.query.order_by(Shop.created_on.desc()).limit(12).all()
    shop = Shop.query.order_by(Shop.created_on.desc()).paginate(page=page_num, per_page=5, error_out=True)
    return render_template('main/shop.html', shop=shop)



@main.route('/detail', methods=['GET'])
@cache.cached(300, key_prefix='detail')
def detail():
    experience_id = request.args.get('id')
    experience = Imageexp.query.filter_by(id=experience_id).first()
    return render_template('main/detail.html', experience=experience)


@main.route('/details', methods=['GET'])
def details():
    id = request.args.get('id2', type=int)
    rating = request.args.get('name')
    experience = Experience.query.get(id)
    rate2 = Rate(rating=rating)
    experience.rates.append(rate2)
    cache.delete('index')
    cache.delete('detail')
    db.session.add(experience)
    db.session.commit()
    return json.dumps({'status': 'OK', 'rating': rating, 'id': id})


# @main.route("/addToCart", methods=['GET', 'POST'])
# @login_required
# def addToCart():
#     # data = request.form['quality']
#     quality=request.form['quality']
#     # quality = request.args.get('quality')
#     expid = int(request.args.get('productid'))
#     user = User.query.get(current_user.id)
#     exp = Experience.query.get(expid)
#     subtotal = float(quality)*float(exp.price)
#     cart = Kart(name=exp.title, quantity=quality, price=exp.price, total=subtotal, user_id=current_user.id, experience_id=expid)
#     user.karts.append(cart)
#     exp.karts.append(cart)
#     db.session.add(user)
#     db.session.add(exp)
#     db.session.commit()
#     return redirect(url_for('experienc.cart'))


# @experienc.route("/cart")
# @login_required
# def cart():
#     noOfItems = getLoginDetails()
#     userId = current_user.id
#     l = []
#     m = { }
#     # products = Kart.query.filter(and_(Kart.user_id == userId, Kart.experience_id == 2)).all()
#     products = Kart.query.filter_by(user_id=userId).all()
#     for p in products:
#         # l.append(p.experience)
#         m.update({p.id: p.experience})
#     totalPrice = 0
#     # for row in products:
#     #     totalPrice += row[2]
    # return render_template("experience/cart.html", product=products, totalPrice=totalPrice, noOfItems=noOfItems)

app/main/templates/main/body.html
{% extends 'main/index.html' %}

{% block phone %}
<div class="">

    <!--storie-->
    <div class="uk-margin-medium">

        <div class="uk-clearfix">
            <div class="uk-float-right">
                <div class="owl-controls">

                </div>
            </div>
            <div class="uk-float-left">
                <p class="uk-text-bold">Tubayo Stories</p>
            </div>
        </div>


        <div uk-slider>

            <div class="uk-position-relative uk-visible-toggle uk-light">

            <ul class="uk-slider-items uk-child-width-1-4 uk-child-width-1-3@m uk-grid uk-grid-collapse" uk-lightbox="animation: slide">
        {% for story in stories %}
        <li style="width: 108px;">
            <a class="uk-inline" href="{{ url_for('admin.uploaded_file', filename=story.filename) }}" caption="{{ story.caption }}">
                <img class="uk-border-circle uk-preserve-width uk-responsive-height uk-responsive-width" src="{{ url_for('admin.uploaded_file', filename=story.filename) }}" style="height:89px; width: 89px;" alt="{{ story.filename}}">
                <div class="uk-text-small uk-text-baseline uk-text-center" style="color:#00421E;">{{ story.story_name }}</div>
            </a>
        </li>
        {% endfor %}
    </ul>


            <a class="uk-position-center-left uk-position-small-out uk-hidden-hover" href="#" uk-slidenav-previous uk-slider-item="previous"></a>
            <a class="uk-position-center-right uk-position-small-out uk-hidden-hover" href="#" uk-slidenav-next uk-slider-item="next"></a>






            </div>

        </div>


    </div>

    <!--end stories-->

    <!--experinces-->

    <div class="uk-margin-remove-top uk-padding-remove-top">
        <div class="uk-clearfix uk-margin-remove-bottom">
            <div class="uk-float-right">
                <a href="#">
                    <button class="uk-button uk-button-text">see all</button>
                </a>
            </div>
            <div class="uk-float-left">
                <p class="uk-text-bold">Experiences</p>
            </div>
        </div>
        <div class="uk-grid-margin uk-grid uk-grid-stack uk-margin-remove-top" uk-grid="">

            <div class="uk-width-1-1@m">
                <div class="uk-margin uk-grid-match uk-child-width-1-1 uk-child-width-1-2@s uk-child-width-1-4@m uk-grid-small uk-grid"
                     uk-grid="">
                    {% for experience in experience %}
                    <div>
                        <a class="uk-link-reset" href="{{ url_for('main.detail', id=experience.id)}}">
                            <div class="uk-panel">
                                <div class="uk-inline">
                                    <img src="{{ url_for('admin.uploaded_file', filename=experience.image.filename) }}"
                                             class="uk-width-small uk-width-medium uk-width-large uk-width-xlarge uk-height-small uk-border-rounded"
                                             style="height:250px;"
                                             alt="experience.image.filename">
                                    <div class="uk-position-top-right uk-overlay uk-padding-small"><i
                                                class="ion-ios-heart-outline" style="font-size: 30px; color: #fff;"></i>
                                    </div>
                                </div>

                                <strong class="uk-text-uppercase uk-text-small uk-text-baseline" style="color:#00421E;">{{ experience.experience.experience_title }} - </strong>
                                <span class="uk-text-uppercase uk-text-bold uk-text-small" style="color:#00421E;">{{experience.experience.place}}</span>
                                <div class="uk-text-meta uk-text-baseline uk-text-small">{{ experience.experience.tag }}</div>

                                <strong class="uk-text-uppercase uk-text-small uk-text-baseline">USD {{ experience.experience.price }} </strong>
                                <span class=" uk-text-small">per person</span>

                                <p class="uk-text-small uk-text-baseline uk-margin-remove-top"><span class="uk-padding-remove-left" style="display: -webkit-inline-box;"><input type="hidden"
                                                    value="{{ experience.experience.rate_average }}"
                                                    name="rateyoid" class="rateyoid"></span> 
                                                {{ experience.experience.rate_average }}</p>

                            </div>
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <!--#end experiences-->

    <!--#shop-->

    <div class=" uk-margin-medium">

        <div class="uk-clearfix">
            <div class="uk-float-right">
                <div class="owl-controls">

                </div>
                <a href="{{ url_for('main.shop')}}">
                    <button class="uk-button uk-button-text">see all</button>
                </a>
            </div>
            <div class="uk-float-left">
                <p class="uk-text-bold">Tubayo Shop</p>
                <!--{{ url_for('static', filename='assets/img/1.jpg')  }}-->
            </div>
        </div>

        <div class="uk-position-relative uk-visible-toggle uk-light uk-margin-left-remove" uk-slider>

            <ul class="uk-slider-items uk-child-width-1-2 uk-child-width-1-4@m uk-grid uk-grid-small">
                {% for item in shop %}
                <li>
                    <div class="uk-panel">
                        <img class="uk-height-small uk-border-rounded" src="{{ url_for('admin.uploaded_file', filename=item.filename) }}" alt="{{ item.filename }}">
                        <div class="uk-text-small uk-text-bold uk-text-baseline" style="color:#00421E;">{{ item.item_name}}</div>
                        <div class="uk-text-small uk-text-baseline" style="color:#00421E;">${{item.price}}</div>
                    </div>
                </li>
                {% endfor %}
            </ul>

            <a class="uk-position-center-left uk-position-small uk-hidden-hover" href="#" uk-slidenav-previous
               uk-slider-item="previous"></a>
            <a class="uk-position-center-right uk-position-small uk-hidden-hover" href="#" uk-slidenav-next
               uk-slider-item="next"></a>

        </div>


    </div>
    <!--#end shop-->
    <!--flyers-->
    <div class="uk-margin-medium">

        <div class="uk-grid-medium uk-grid-divider uk-child-width-1-2@m uk-grid-small uk-text-center" uk-grid>
            {% for flyer in flyers %}
            <div>
                <div class="uk-card uk-height-medium">
                    <div class="uk-card-media-top">
                        <img class="uk-height-small " style=' height:230px;' width="643" src="{{ url_for('admin.uploaded_file', filename=flyer.filename) }}" alt="{{ flyer.filename }}">
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <!--end flyers-->

    <!--trending-->
    <div class="uk-margin-medium">
        <div class="uk-position-relative uk-visible-toggle uk-light" uk-slider>

            <ul class="uk-slider-items uk-child-width-1-2 uk-child-width-1-4@m uk-grid uk-grid-small">
                {% for experience in experience %}
                <li>
                    <div class="uk-panel">
                        <div class="uk-inline">
                            <img src="{{ url_for('admin.uploaded_file', filename=experience.image.filename) }}"
                                     class="uk-width-small uk-width-medium uk-width-large uk-width-xlarge uk-height-small uk-border-rounded"
                                     style="height:250px;"
                                     alt="experience.image.alt">
                            <div class="uk-position-top-right uk-overlay uk-padding-small"><i
                                        class="ion-ios-heart-outline" style="font-size: 30px; color: #fff;"></i>
                            </div>
                        </div>

                        <strong class="uk-text-uppercase uk-text-small uk-text-baseline" style="color:#00421E;">{{ experience.experience.experience_title }} - </strong>
                        <span class="uk-text-uppercase uk-text-bold uk-text-small" style="color:#00421E;">{{experience.experience.place}}</span>
                        <div class="uk-text-meta uk-text-baseline uk-text-small">{{ experience.experience.tag }}</div>

                        <strong class="uk-text-uppercase uk-text-small uk-text-baseline">USD {{ experience.experience.price }} </strong>
                        <span class=" uk-text-small">per person</span>

                        <div class="uk-margin-remove-bottom uk-grid-collapse uk-margin-remove-bottom uk-text-baseline" uk-grid>
                                <div class="uk-width-auto uk-margin-remove-bottom "><span
                                        class="rateYo uk-padding-remove-left"><input type="hidden"
                                                                value="{{ experience.experience.rate_average }}"
                                                                name="rateyoid"
                                                                class="rateyoid">
                                                            </span>
                                </div>
                                <div class="uk-width-expand uk-margin-remove-bottom"><p class="uk-text-meta uk-margin-remove-bottom">{{
                                    experience.experience.rate_average }}</p></div>
                            </div>

                    </div>
                </li>
                {% endfor %}
            </ul>

            <a class="uk-position-center-left uk-position-small uk-hidden-hover" href="#" uk-slidenav-previous
               uk-slider-item="previous"></a>
            <a class="uk-position-center-right uk-position-small uk-hidden-hover" href="#" uk-slidenav-next
               uk-slider-item="next"></a>

        </div>
    </div>
    <!--end of trending-->

</div>
{% endblock %}

app/main/templates/main/detail.html
{% extends 'layout.html' %}

{% block stylesheet %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.css">
{% endblock %}

{% block body%}

<div class="uk-container uk-margin">
    <div class="uk-margin-xlarge uk-grid" uk-grid="">

        <div class="uk-width-expand@m uk-first-column uk-border-rounded">
            <div class="uk-panel uk-border-rounded">
                <div class="uk-border-rounded uk-position-relative uk-margin uk-width-large uk-margin-auto uk-text-left@m uk-text-center uk-slideshow uk-light"
                    uk-slideshow="minHeight: 550;maxHeight: 1150;autoplay: true">

                    <ul class="uk-slideshow-items" style="min-height: 550px; height: 550px;">
                        {% for image in experience.experience.images.all() %}
                        <li>
                            <img class="uk-border-rounded" src="{{ url_for('admin.uploaded_file', filename=experience.image.filename) }}" alt="image.filename" uk-cover>
                        </li>
                        {% endfor %}
                    </ul>

                    <a class="uk-position-center-left uk-position-small uk-hidden-hover" href="#" uk-slidenav-previous uk-slideshow-item="previous"></a>
                    <a class="uk-position-center-right uk-position-small uk-hidden-hover" href="#" uk-slidenav-next uk-slideshow-item="next"></a>

                </div>
                <div class="uk-position-relative uk-margin uk-width-large uk-margin-auto">
                    <div class="uk-clearfix uk-margin-remove-bottom">
                        <div class="uk-float-right">
                            <a href="#">
                                <a class="uk-button uk-button-default uk-button-large" href="#booking">see dates</a>
                            </a>
                        </div>
                        <div class="uk-float-left">
                            <div class="uk-text-meta uk-margin-remove-bottom">${{ experience.experience.price }} per person</div>
                            <span class="rateYo uk-text-small uk-margin-remove-bottom"><input type="hidden" value="{{ experience.experience.rate_average }}" name="rateyoid" class="rateyoid"></span>
                            <div class="counter"></div>
                        </div>
                    </div>

                </div>

            </div>

            <div class="uk-section">
                <h2 id="booking" class="uk-margin">dates available</h2>
                <table class="uk-table uk-table-striped">
                <thead>
                <tr>
                    <th>Date</th>
                    <th>No of people</th>
                    <th>@Price</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td></td>
                    <td class="">
                        <input id="quality" name="quality" type="number" class="uk-input uk-form-width-small" step="1" min="0" max="" value="1" title="Qty"
                                                size="4" pattern="[0-9]*" inputmode="numeric">
                    </td>
                    <td>
                        <a href=""class="uk-button uk-button-default" type="submit">Button</a>
                    </td>
                </tr>
                </tbody>
            </table>

                <table class="uk-table uk-table-justify uk-table-divider uk-table-small">
                    <thead>
                        <tr>
                            <th class="uk-width-small">Date</th>
                            <th>Number of people</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>8:00</td>
                            <td>
                                <form class="uk-form-horizontal uk-margin" action="#" method="Post">
                                    <div class="uk-margin">

                                        <div class="uk-form-controls">
                                            <input id="quality" name="quality" type="number" class="uk-input uk-form-width-small" step="1" min="0" max="" value="1" title="Qty"
                                                size="4" pattern="[0-9]*" inputmode="numeric">

                                        </div>
                                        <button class="uk-button uk-button-default" type="submit">Button</button>
                                    </div>
                                </form>
                            </td>
                        </tr>
                    </tbody>
                </table>

            </div>
        </div>

        <div class="uk-width-expand@m">

            <div>

                <h2 class="uk-text-bold">{{ experience.experience.experience_title }}</h2>
                <p class="uk-text-meta">{{ experience.experience.place }} · {{ experience.experience.tag }}</p>
                <div class="uk-clearfix">
                    <div class="uk-float-right">
                        <img id="avatar" width="50" class="uk-border-circle uk-text-center uk-margin-small-top" src="https://orig00.deviantart.net/c91f/f/2010/014/b/c/avatar_by_eggar919.jpg">
                    </div>
                    <div class="uk-float-left">
                        <p class="uk-text-bold uk-padding-remove">Food & drink experience</p>
                        <p class="uk-text-meta uk-padding-remove">Hosted by {{experience.experience.host_name}}</p>
                    </div>
                </div>
                <div class="uk-text-center" uk-grid>
                    <div class="uk-width-auto">
                        <span uk-icon="icon: camera"></span>
                    </div>
                    <div class="uk-width-expand">
                        <div>1.5 hours total</div>
                    </div>
                </div>
                <div class="uk-text-center" uk-grid>
                    <div class="uk-width-auto">
                        <span uk-icon="icon: camera"></span>
                    </div>
                    <div class="uk-width-expand">
                        <div>1 snack and Drinks</div>
                    </div>
                </div>
                <div class="uk-text-center" uk-grid>
                    <div class="uk-width-auto">
                        <span uk-icon="icon: camera"></span>
                    </div>
                    <div class="uk-width-expand uk-padding-remove uk-margin-remove">
                        <div>Offered in English and French</div>
                    </div>
                </div>
                <hr>
                <dl class="uk-description-list uk-description-list-divider">
                    <!-- <dt class="uk-h3 uk-text-bold">Description term</dt> -->
                    <dd>There’s only one spot left. Join 4 others at Pablo’s experience next Tuesday.</dd>
                    <dt class="uk-h3 uk-text-bold">About your host, Pablo</dt>
                    <dd>{{ experience.experience.about_experience }}</dd>

                    <dt class="uk-h3 uk-text-bold">What we’ll do</dt>
                    <dd>{{ experience.experience.what_well_do }}</dd>

                    <dt class="uk-h3 uk-text-bold">What I’ll provide</dt>
                    <dd>Yumi Juice
                        <span uk-icon="icon: camera"></span>
                    </dd>
                    <dd>Delicious and complex juice, combining vegetables, fruits and herbs.</dd>
                    <dd>Micro green salad
                        <span uk-icon="icon: camera"></span>
                    </dd>
                    <dd>Ultra-local salad of micro greens</dd>

                    <dt class="uk-h3 uk-text-bold">Who can come</dt>
                    <dd>{{ experience.experience.who_can_come }}</dd>
                </dl>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block script %}
<script src="https://code.jquery.com/jquery-3.2.1.min.js"
        integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.js"></script>

<script>
            $(function () {
                $("input.rateyoid").each(function () {
                    var current_rating = $(this).val();
                    var id = '{{ experience.experience.id }}';
                    $(this).parent().rateYo({
                        starWidth: "20px",
                        halfStar: true,
                        rating: current_rating
                        
                    }).on("rateyo.set", function (e, data) {
                        $(".counter").text(data.rating)
                        console.log("set event is fired on click3333")
                        $.ajax({
                            type: "GET",
                            url: "{{ url_for('main.details')}}",
                            contentType: "application/json; charset=utf-8",
                            data: { name: data.rating,
                                    id2: id
                             },
                            success: function (response) {
                                console.log(response)
                            }

                        });
                    })
                    .on("rateyo.change", function (e, data) {
                        console.log("set event is fired on click")
                        var rating = data.rating;
                        $(this).next().text(rating);
                      });
            });
            $(".rateYo").rateYo();
        });
    </script>
{% endblock %}

app/main/templates/main/index.html
{% extends 'layout.html' %}
{% set active_page = "index" %}

{% block stylesheet %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.css">

{% endblock %}

{% block body%}

<div class="">
    <div class="uk-position-relative uk-visible-toggle uk-light uk-box-shadow-small"  uk-slideshow="min-height: 175; max-height: 300; animation: push; autoplay: true; autoplay-interval: 5000; pause-on-hover: true">

    <ul class="uk-slideshow-items">
        {% for slideshow in slideshow %}
            <li>
                <img class="uk-preserve-width uk-responsive-height uk-responsive-width" src="{{ url_for('admin.uploaded_file', filename=slideshow.filename) }}" alt="{{ slideshow.filename }}" uk-cover uk-responsive>
            </li>
        {% endfor %}
    </ul>

    <a class="uk-position-center-left uk-position-small uk-hidden-hover" href="#" uk-slidenav-previous uk-slideshow-item="previous"></a>
    <a class="uk-position-center-right uk-position-small uk-hidden-hover" href="#" uk-slidenav-next uk-slideshow-item="next"></a>

</div>
</div>

<div class="uk-container uk-margin uk-container-large">

    <div class="uk-hidden@l">
        {% block phone %}{% endblock %}
    </div>
    <div class="uk-visible@l">
        <div uk-grid>
            <div class="uk-width-3-4 uk-row-first">{{ self.phone() }}</div>
            <div class="uk-width-1-4">
                <div class="uk-flex uk-flex-column">
                   
                    {% for advert in adverts %}
                    <div class="uk-panel uk-margin-top">
                        <img class="uk-height-large uk-flex uk-flex-center uk-flex-middle uk-responsive-width uk-responsive-height" src="{{ url_for('admin.uploaded_file', filename=advert.filename) }}" alt="{{ advert.filename }}">

                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

</div>

{% endblock %}

{% block script %}

<script src="https://code.jquery.com/jquery-3.2.1.min.js"
        integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.js"></script>
<script>
    $(function () {
        $("input.rateyoid").each(function () {
            var current_rating = $(this).val();

            $(this).parent().rateYo({
                starWidth: "12px",
                halfStar: true,
                rating: current_rating,
                readOnly: true
            }).on("rateyo.change", function (e, data) {
                $(".counter").text(data.rating)

            });
        });
    });
</script>

{% endblock %}

app/main/templates/main/shop.html
{% from 'paginate.html' import render_pagination %}
{% extends 'layout.html' %}
{% set active_page = "shop" %}
{% block body %}

	<div class="uk-section uk-container">
		<h3>Shop Items</h3>
		<div class="uk-child-width-1-4@m uk-child-width-1-1@s uk-grid-small uk-text-center" uk-grid>
			{% for item in shop.items %}
		        <div class="uk-panel">
		            <img class="uk-height-small uk-border-rounded" src="{{ url_for('admin.uploaded_file', filename=item.filename) }}" alt="{{ item.filename }}">
		            <div class="uk-text-small uk-text-bold uk-text-baseline" style="color:#00421E;">{{ item.item_name}}</div>
		            <div class="uk-text-small uk-text-baseline" style="color:#00421E;">${{item.price}}</div>
		        </div>
		    {% endfor %}
		</div>
		<!--Pagination -->
		{% if shop.pages >1 %}
		{{ render_pagination( shop, 'main.shop') }}
		{% endif %}
		<!--/Pagination -->
	</div>

{% endblock %}